### ISSUE TITLE
64bits

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-event-kit#1]
Hi, could it be compiled for 64bits 4D MacOSX ?
Thx

**Comment by miyako** [comment]
The plugin is current using an internal bridge application to use 64-bit API in a 32-bit context.
Porting it to 64-bit entails that the calls are made directly; that requires rewrite of all commands.
Today I did 5 commands, but there is still a lot more to go...

**Comment by miyako** [comment]
I've completed the rewrite, but since it is not a simple recompile, you should test the features and make sure that there are no issues.
