### ISSUE TITLE
Catalina Calendar Access

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-event-kit#7]
Hi Miyako,

do I have to add at the end of the build app info.plist the key

com.apple.security.personal-information.calendars ?

Regarding your previous hints I have added

    <key>NSRequiresAquaSystemAppearance</key>
    <string>Yes</string>
    <key>NSAppleEventsUsageDescription</key>
    <string/>
    <key>NSCalendarsUsageDescription</key>
    <string/>
    <key>NSContactsUsageDescription</key>
    <string/>
    <key>NSCameraUsageDescription</key>
    <string/>
    <key>NSMicrophoneUsageDescription</key>
    <string/>

and for Catalina it should look like this ?

    <key>NSRequiresAquaSystemAppearance</key>
    <string>Yes</string>
    <key>NSAppleEventsUsageDescription</key>
    <string/>
    <key>NSCalendarsUsageDescription</key>
    <string/>
    <key>NSContactsUsageDescription</key>
    <string/>
    <key>NSCameraUsageDescription</key>
    <string/>
    <key>NSMicrophoneUsageDescription</key>
    <string/>
    **<key>com.apple.security.personal-information.calendars</key>
    <string/>
    <key>com.apple.security.personal-information.addressbook</key>
    <string/>**

Thanks Armin

**Comment by miyako** [comment]
one should not confuse plist keys with entitlements.

``com.apple.security.personal-information.calendars`` is an entitlement, so it is pointless to add it literally to info.plist.

you need to create an entitlement xml and pass its path to ``codesign``.

see the example in https://github.com/miyako/4d-utility-build-application

**Comment by ArminDeeg** [comment]
Thanks Miyako,

do you have an example how to do it ?

Inside your code for build application I can't find an example for this.

Armin

**Comment by miyako** [comment]
in the method ``codesign`` there is an example.

**Comment by miyako** [comment]
if you download the latest copy of "build application"
and use it "as is" (just change $path:=...)
it will add the necessary attributes.
