### ISSUE TITLE
Event Kit v 2.0 from oct. 14th 2019 does not work

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-event-kit#8]
4D 17 R6 build 17R6.243126
macOS 10.13.6

Screenshot from the latest version
sample, it seems that no plugin command returns a valid information

<img width="729" alt="Bildschirmfoto 2019-10-19 um 14 04 48" src="https://user-images.githubusercontent.com/6436037/67144751-a0402100-f27a-11e9-9b98-f52f5c54032c.png">

**sample from the previous version from nov. 7th 2018**

<img width="749" alt="Bildschirmfoto 2019-10-19 um 14 02 47" src="https://user-images.githubusercontent.com/6436037/67144775-e09f9f00-f27a-11e9-81c8-94c4d06b699b.png">

Regards Armin

**Comment by miyako** [comment]
you need to call ``EK_Request_permisson`` first

**Comment by ArminDeeg** [comment]
Hi, when I try the new plugin with

macOS 10.13.6
4D v17r6 final merged with volume desktop notarized app with your "build application"

it crashes at this point: $status:=EK Request permisson (EK Calendar Event)

**Comment by miyako** [comment]
if you didn't notarise your app with the necessary entitlements,
a crash is the correct behaviour.

**Comment by miyako** [comment]
the apple api to request permission was introduced in 10.14.

**Comment by miyako** [comment]
sorry, 10.9

https://github.com/miyako/4d-plugin-event-kit/blob/master/event-kit/4DPlugin-Event-Kit.cpp

**Comment by miyako** [comment]
unfortunately I've already updated to 10.15, I can't test 10.13 anymore.

**Comment by miyako** [comment]
I appreciate your reports and would like to fix it one day, 
but right now I have too many projects, someone else with more resources should look into it.

**Comment by ArminDeeg** [comment]
What is missing ?

I thought that your latest build application tool adds all needed entitlements

![Bildschirmfoto 2019-11-22 um 14 56 54](https://user-images.githubusercontent.com/6436037/69431705-9194d000-0d38-11ea-82c0-e33664ec7a1d.png)

**Comment by miyako** [comment]
for me, the problem is that the plugin has too many commands that nobody is using. it seems like 95% of the code is unnecessary.

**Comment by miyako** [comment]
when the system has crashed the app for entitlement or notarisation reasons, normally there is a comment in the console sys log.

**Comment by ArminDeeg** [comment]
I use
$ev_obj:=EK Request permisson (EK Calendar Event)
EK CALENDAR LIST (arT_evtCalIDs;EK Calendar Event)
$success:=EK CALENDAR Get title (arT_evtCalIDs{$i};$CalendarTitle)
$success:=EK CALENDAR Get type (arT_evtCalIDs{$i};$CalendarType)

$success:=EK CALENDAR Get default (EK Calendar Event;$vt_icalCalID)

$success:=EK ITEM Get title ($vt_ExpoID;$title)
$event:=EK EVENT Create ($vt_calID)
$success:=EK EVENT Set end date ($event;$vd_terminDate;$vT_TerminZeitBis)
$success:=EK EVENT Set start date ($event;$vd_terminDate;$vT_TerminZeitVon)
$success:=EK ITEM Set location ($event;$vt_Ort)
$success:=EK ITEM Set notes ($event;$vt_Notiz)
$success:=EK ITEM Set title ($event;$vt_Titel)

**Comment by miyako** [comment]
that proves my point. 
it would be much faster to create a new plugin with just the basic features than invest a huge amount of time trying to support this or "ical" which has more than 100 commands.

**Comment by ArminDeeg** [comment]
Fixed
