### ISSUE TITLE
NSCalendarsUsageDescription

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-event-kit#9]
Hi Keisuke

how to create this file NSCalendarsUsageDescription and where to install it?

Thanks

**Comment by ArminDeeg** [comment]
Look inside this tool 
It signs notarize and adds all needed keys 

`https://github.com/miyako/4d-utility-build-application`

**Comment by ArminDeeg** [comment]
clickable link: 
[ Click](https://github.com/miyako/4d-utility-build-application) 
Armin

**Comment by MatthieuLamp** [comment]
even after signing, it's not ok
my app crash

**Comment by ArminDeeg** [comment]
You load maybe the wrong version, you have to load from "releases" Version 2.1.v17 or 2.1.v18

not "clone or download"

**Comment by ArminDeeg** [comment]
old version with higher release number 2.2 crashes, 2.1 is newer and does not crash anymore Miyako should delete the 2.2 release and also 2.0 release which crashes too.

**Comment by MatthieuLamp** [comment]
Test with 2.1, 4D 18 and Catalina, my app crash again

**Comment by ArminDeeg** [comment]
Check the plugin bundle version

> Event Kit version 2.1, Copyright 2020 miyako.

Please respond where it crashes.

You have to call EK Request permisson first

I use a combination of these commands:


ARRAY TEXT($ical_CalNames;0)
ARRAY TEXT($eventCalendarsID;0)
C_OBJECT($ev_obj)
$ev_obj:=EK Request permisson (EK Calendar Event)
If ($ev_obj.success)
	EK CALENDAR LIST ($eventCalendarsID;EK Calendar Event)
	ARRAY TEXT(arT_iCalIDs;0)
	ARRAY TEXT(arT_iCalNames;0)
	For ($i;0;Size of array($eventCalendarsID))
		$success:=EK CALENDAR Get title ($eventCalendarsID{$i};$CalendarTitle)
		$success:=EK CALENDAR Get type ($eventCalendarsID{$i};$CalendarType)
		If ($CalendarType=0) | ($CalendarType=1) | ($CalendarType=2)
			APPEND TO ARRAY(arT_iCalIDs;$eventCalendarsID{$i})
			APPEND TO ARRAY(arT_iCalNames;$CalendarTitle)
		End if 
	End for 
End if 

compile code and build with volume desktop app and sign it with the Miyako tool, to get the needed keys inside the build app

		$event:=EK EVENT Create ($vt_calID)
			$success:=EK EVENT Set end date ($event;$vd_terminDate;$vT_TerminZeitBis)
			$success:=EK EVENT Set start date ($event;$vd_terminDate;$vT_TerminZeitVon)
			$success:=EK ITEM Set location ($event;$vt_Ort)
			$success:=EK ITEM Set notes ($event;$vt_Notiz)
			$success:=EK ITEM Set title ($event;$vt_Titel)

**Comment by MatthieuLamp** [comment]
the bug is with the creation of reminders
does it work for you creating a reminder ?

**Comment by ArminDeeg** [comment]
I don‘t use reminders, if you like to geht help from Miyako, create a debug log and check which command crashes the app, this is unpaid freeware and Miyako is very busy.

Paste your code and the macos crash log and 4d current method debug log

**Comment by MatthieuLamp** [comment]
it is after this command that 4D crashes :
$success:=EK CALENDAR Get default (EK Calendar Reminder;$calendar)

**Comment by MatthieuLamp** [comment]
after the terminal it's OK
tccutil reset Reminders com.4d.4d
tccutil reset AddressBook com.4d.4d
tccutil reset Calendar com.4d.4d
